insert into STUDENT values(1,11,'jithin')
insert into STUDENT values(2,12,'sam')
insert into STUDENT values(3,13,'tony')
insert into STUDENT values(4,14,'mathew')
insert into STUDENT values(5,15,'savior')